# These are supported funding model platforms

github: tosolommy
patreon: maanav1647
open_collective: maanav1647
ko_fi: Asano Hiroshi
tidelift: bytedance/deer-flow
community_bridge: deer-flow
liberapay: LangChain
issuehunt: # Replace with a single IssueHunt username
lfx_crowdfunding: # Replace with a single LFX Crowdfunding project-name e.g., cloud-foundry
polar: # Replace with a single Polar username
buy_me_a_coffee: # Replace with a single Buy Me a Coffee username
thanks_dev: # Replace with a single thanks.dev username
custom: # Replace with up to 4 custom sponsorship URLs e.g., ['link1', 'link2']
